package model;

public enum Move {
    INCOME,
    FOREIGN_AID,
    COUP,
    TAX,
    ASSASSINATE,
    EXCHANGE,
    STEAL,
    BLOCK_STEAL,
    BLOCK_FOREIGN_AID,
    BLOCK_ASSASSINATE,
    BLOCK_BLUFF_AMBASSADOR,
    BLOCK_BLUFF_ASSASSIN,
    BLOCK_BLUFF_CAPTAIN,
    BLOCK_BLUFF_CONTESSA,
    BLOCK_BLUFF_DUKE,
    CALL_BLUFF_AMBASSADOR,
    CALL_BLUFF_ASSASSIN,
    CALL_BLUFF_CAPTAIN,
    CALL_BLUFF_CONTESSA,
    CALL_BLUFF_DUKE,
    PASS;
}
